#!/bin/sh -ef
#
# Run EDNA2html.py
#
# NB Need to set the EDNA2HTMLDIR environment variable to the
# location of the EDNA2html.py program
#
# CVS_id $Id: EDNA2html,v 1.1.1.1 2010/03/08 13:50:45 pjb93 Exp $
#
# Set up the environment
##export EDNA2HTMLDIR=/home/pjb/Diamond/EDNA2html
export EDNA2HTMLDIR=/home/pjb93/EDNA2html
# Run the EDNA2html.py script
python ${EDNA2HTMLDIR}/EDNA2html.py ${1+"$@"}
#

