
suggestedStrategy = """<suggestedStrategy>
        <bestLogFile>
            <path>
                <value>/users/opid14/dawb_workspace/id14eh4/edna-working-dir/test_complete/20110603_042905/ControlCharForReorientationv2_0-00000079/MXv2KappaStrategy/ControlStrategyv1_2/Bestv1_2/best.log</value>
            </path>
        </bestLogFile>
        <collectionPlan>
            <collectionPlanNumber>
                <value>1</value>
            </collectionPlanNumber>
            <collectionStrategy>
                <diffractionPlan>
                    <complexity>
                        <value>full</value>
                    </complexity>
                    <kappaStrategyOption>
                        <value>Cell</value>
                    </kappaStrategyOption>
                    <maxExposureTimePerDataCollection>
                        <value>1.000000e+03</value>
                    </maxExposureTimePerDataCollection>
                </diffractionPlan>
                <subWedge>
                    <experimentalCondition>
                        <beam>
                            <exposureTime>
                                <value>1.000000e-01</value>
                            </exposureTime>
                            <wavelength>
                                <value>9.792000e-01</value>
                            </wavelength>
                        </beam>
                        <detector>
                            <beamPositionX>
                                <value>1.575200e+02</value>
                            </beamPositionX>
                            <beamPositionY>
                                <value>1.566130e+02</value>
                            </beamPositionY>
                            <bin>
                                <value>2x2</value>
                            </bin>
                            <byteOrder>
                                <value>little_endian</value>
                            </byteOrder>
                            <dataType>
                                <value>unsigned_short</value>
                            </dataType>
                            <distance>
                                <value>3.408000e+02</value>
                            </distance>
                            <imageSaturation>
                                <value>65535</value>
                            </imageSaturation>
                            <name>
                                <value>ADSC Q315 bin 2x2</value>
                            </name>
                            <numberBytesInHeader>
                                <value>512</value>
                            </numberBytesInHeader>
                            <numberPixelX>
                                <value>3072</value>
                            </numberPixelX>
                            <numberPixelY>
                                <value>3072</value>
                            </numberPixelY>
                            <pixelSizeX>
                                <value>1.025880e-01</value>
                            </pixelSizeX>
                            <pixelSizeY>
                                <value>1.025880e-01</value>
                            </pixelSizeY>
                            <serialNumber>
                                <value>918</value>
                            </serialNumber>
                            <type>
                                <value>q315-2x</value>
                            </type>
                        </detector>
                        <goniostat>
                            <oscillationWidth>
                                <value>5.000000e-01</value>
                            </oscillationWidth>
                            <rotationAxis>
                                <value>phi</value>
                            </rotationAxis>
                            <rotationAxisEnd>
                                <value>9.100000e+01</value>
                            </rotationAxisEnd>
                            <rotationAxisStart>
                                <value>9.050000e+01</value>
                            </rotationAxisStart>
                        </goniostat>
                    </experimentalCondition>
                    <image>
                        <date>
                            <value>Wed Jun  1 16:51:32 2011</value>
                        </date>
                        <number>
                            <value>2</value>
                        </number>
                        <path>
                            <value>/data/id14eh4/inhouse/opid144/20110601/RAW_DATA/ref-edna_1_0002.img</value>
                        </path>
                    </image>
                </subWedge>
                <subWedge>
                    <experimentalCondition>
                        <beam>
                            <exposureTime>
                                <value>1.000000e-01</value>
                            </exposureTime>
                            <wavelength>
                                <value>9.792000e-01</value>
                            </wavelength>
                        </beam>
                        <detector>
                            <beamPositionX>
                                <value>1.575200e+02</value>
                            </beamPositionX>
                            <beamPositionY>
                                <value>1.566130e+02</value>
                            </beamPositionY>
                            <bin>
                                <value>2x2</value>
                            </bin>
                            <byteOrder>
                                <value>little_endian</value>
                            </byteOrder>
                            <dataType>
                                <value>unsigned_short</value>
                            </dataType>
                            <distance>
                                <value>3.408000e+02</value>
                            </distance>
                            <imageSaturation>
                                <value>65535</value>
                            </imageSaturation>
                            <name>
                                <value>ADSC Q315 bin 2x2</value>
                            </name>
                            <numberBytesInHeader>
                                <value>512</value>
                            </numberBytesInHeader>
                            <numberPixelX>
                                <value>3072</value>
                            </numberPixelX>
                            <numberPixelY>
                                <value>3072</value>
                            </numberPixelY>
                            <pixelSizeX>
                                <value>1.025880e-01</value>
                            </pixelSizeX>
                            <pixelSizeY>
                                <value>1.025880e-01</value>
                            </pixelSizeY>
                            <serialNumber>
                                <value>918</value>
                            </serialNumber>
                            <type>
                                <value>q315-2x</value>
                            </type>
                        </detector>
                        <goniostat>
                            <oscillationWidth>
                                <value>5.000000e-01</value>
                            </oscillationWidth>
                            <rotationAxis>
                                <value>phi</value>
                            </rotationAxis>
                            <rotationAxisEnd>
                                <value>9.100000e+01</value>
                            </rotationAxisEnd>
                            <rotationAxisStart>
                                <value>9.050000e+01</value>
                            </rotationAxisStart>
                        </goniostat>
                    </experimentalCondition>
                    <image>
                        <date>
                            <value>Wed Jun  1 16:51:32 2011</value>
                        </date>
                        <number>
                            <value>2</value>
                        </number>
                        <path>
                            <value>/data/id14eh4/inhouse/opid144/20110601/RAW_DATA/ref-edna_1_0002.img</value>
                        </path>
                    </image>
                </subWedge>
            </collectionStrategy>
            <comment>
                <value>OMEGA=258.773 KAPPA=3.021 PHI=268.834 STRATEGY=MERGED</value>
            </comment>
            <statistics>
                <resolutionBin>
                    <IOverSigma>
                        <value>3.290000e+01</value>
                    </IOverSigma>
                    <averageIntensity>
                        <value>1.388690e+03</value>
                    </averageIntensity>
                    <averageIntensityOverAverageSigma>
                        <value>3.180000e+01</value>
                    </averageIntensityOverAverageSigma>
                    <averageSigma>
                        <value>4.368500e+01</value>
                    </averageSigma>
                    <completeness>
                        <value>9.800000e-01</value>
                    </completeness>
                    <maxResolution>
                        <value>8.390000e+00</value>
                    </maxResolution>
                    <minResolution>
                        <value>1.200000e+01</value>
                    </minResolution>
                    <percentageOverload>
                        <value>0.000000e+00</value>
                    </percentageOverload>
                    <rFactor>
                        <value>3.600000e+00</value>
                    </rFactor>
                    <redundancy>
                        <value>3.220000e+00</value>
                    </redundancy>
                </resolutionBin>
                <resolutionBin>
                    <IOverSigma>
                        <value>2.760000e+01</value>
                    </IOverSigma>
                    <averageIntensity>
                        <value>8.905740e+02</value>
                    </averageIntensity>
                    <averageIntensityOverAverageSigma>
                        <value>2.630000e+01</value>
                    </averageIntensityOverAverageSigma>
                    <averageSigma>
                        <value>3.380800e+01</value>
                    </averageSigma>
                    <completeness>
                        <value>9.900000e-01</value>
                    </completeness>
                    <maxResolution>
                        <value>6.830000e+00</value>
                    </maxResolution>
                    <minResolution>
                        <value>8.390000e+00</value>
                    </minResolution>
                    <percentageOverload>
                        <value>0.000000e+00</value>
                    </percentageOverload>
                    <rFactor>
                        <value>4.400000e+00</value>
                    </rFactor>
                    <redundancy>
                        <value>3.320000e+00</value>
                    </redundancy>
                </resolutionBin>
                <resolutionBin>
                    <IOverSigma>
                        <value>2.270000e+01</value>
                    </IOverSigma>
                    <averageIntensity>
                        <value>6.622970e+02</value>
                    </averageIntensity>
                    <averageIntensityOverAverageSigma>
                        <value>2.140000e+01</value>
                    </averageIntensityOverAverageSigma>
                    <averageSigma>
                        <value>3.095900e+01</value>
                    </averageSigma>
                    <completeness>
                        <value>9.900000e-01</value>
                    </completeness>
                    <maxResolution>
                        <value>5.900000e+00</value>
                    </maxResolution>
                    <minResolution>
                        <value>6.830000e+00</value>
                    </minResolution>
                    <percentageOverload>
                        <value>0.000000e+00</value>
                    </percentageOverload>
                    <rFactor>
                        <value>5.300000e+00</value>
                    </rFactor>
                    <redundancy>
                        <value>3.170000e+00</value>
                    </redundancy>
                </resolutionBin>
                <resolutionBin>
                    <IOverSigma>
                        <value>2.250000e+01</value>
                    </IOverSigma>
                    <averageIntensity>
                        <value>7.295770e+02</value>
                    </averageIntensity>
                    <averageIntensityOverAverageSigma>
                        <value>2.140000e+01</value>
                    </averageIntensityOverAverageSigma>
                    <averageSigma>
                        <value>3.415800e+01</value>
                    </averageSigma>
                    <completeness>
                        <value>9.900000e-01</value>
                    </completeness>
                    <maxResolution>
                        <value>5.270000e+00</value>
                    </maxResolution>
                    <minResolution>
                        <value>5.900000e+00</value>
                    </minResolution>
                    <percentageOverload>
                        <value>0.000000e+00</value>
                    </percentageOverload>
                    <rFactor>
                        <value>5.400000e+00</value>
                    </rFactor>
                    <redundancy>
                        <value>3.300000e+00</value>
                    </redundancy>
                </resolutionBin>
                <resolutionBin>
                    <IOverSigma>
                        <value>2.490000e+01</value>
                    </IOverSigma>
                    <averageIntensity>
                        <value>9.854700e+02</value>
                    </averageIntensity>
                    <averageIntensityOverAverageSigma>
                        <value>2.380000e+01</value>
                    </averageIntensityOverAverageSigma>
                    <averageSigma>
                        <value>4.144600e+01</value>
                    </averageSigma>
                    <completeness>
                        <value>9.900000e-01</value>
                    </completeness>
                    <maxResolution>
                        <value>4.810000e+00</value>
                    </maxResolution>
                    <minResolution>
                        <value>5.270000e+00</value>
                    </minResolution>
                    <percentageOverload>
                        <value>0.000000e+00</value>
                    </percentageOverload>
                    <rFactor>
                        <value>4.900000e+00</value>
                    </rFactor>
                    <redundancy>
                        <value>3.380000e+00</value>
                    </redundancy>
                </resolutionBin>
                <resolutionBin>
                    <IOverSigma>
                        <value>2.640000e+01</value>
                    </IOverSigma>
                    <averageIntensity>
                        <value>1.224341e+03</value>
                    </averageIntensity>
                    <averageIntensityOverAverageSigma>
                        <value>2.530000e+01</value>
                    </averageIntensityOverAverageSigma>
                    <averageSigma>
                        <value>4.837900e+01</value>
                    </averageSigma>
                    <completeness>
                        <value>9.900000e-01</value>
                    </completeness>
                    <maxResolution>
                        <value>4.450000e+00</value>
                    </maxResolution>
                    <minResolution>
                        <value>4.810000e+00</value>
                    </minResolution>
                    <percentageOverload>
                        <value>0.000000e+00</value>
                    </percentageOverload>
                    <rFactor>
                        <value>4.700000e+00</value>
                    </rFactor>
                    <redundancy>
                        <value>3.430000e+00</value>
                    </redundancy>
                </resolutionBin>
                <resolutionBin>
                    <IOverSigma>
                        <value>2.600000e+01</value>
                    </IOverSigma>
                    <averageIntensity>
                        <value>1.234242e+03</value>
                    </averageIntensity>
                    <averageIntensityOverAverageSigma>
                        <value>2.490000e+01</value>
                    </averageIntensityOverAverageSigma>
                    <averageSigma>
                        <value>4.951000e+01</value>
                    </averageSigma>
                    <completeness>
                        <value>9.900000e-01</value>
                    </completeness>
                    <maxResolution>
                        <value>4.160000e+00</value>
                    </maxResolution>
                    <minResolution>
                        <value>4.450000e+00</value>
                    </minResolution>
                    <percentageOverload>
                        <value>0.000000e+00</value>
                    </percentageOverload>
                    <rFactor>
                        <value>4.800000e+00</value>
                    </rFactor>
                    <redundancy>
                        <value>3.520000e+00</value>
                    </redundancy>
                </resolutionBin>
                <resolutionBin>
                    <IOverSigma>
                        <value>2.420000e+01</value>
                    </IOverSigma>
                    <averageIntensity>
                        <value>1.121024e+03</value>
                    </averageIntensity>
                    <averageIntensityOverAverageSigma>
                        <value>2.310000e+01</value>
                    </averageIntensityOverAverageSigma>
                    <averageSigma>
                        <value>4.844000e+01</value>
                    </averageSigma>
                    <completeness>
                        <value>9.900000e-01</value>
                    </completeness>
                    <maxResolution>
                        <value>3.920000e+00</value>
                    </maxResolution>
                    <minResolution>
                        <value>4.160000e+00</value>
                    </minResolution>
                    <percentageOverload>
                        <value>0.000000e+00</value>
                    </percentageOverload>
                    <rFactor>
                        <value>5.200000e+00</value>
                    </rFactor>
                    <redundancy>
                        <value>3.480000e+00</value>
                    </redundancy>
                </resolutionBin>
                <resolutionBin>
                    <IOverSigma>
                        <value>2.250000e+01</value>
                    </IOverSigma>
                    <averageIntensity>
                        <value>1.004373e+03</value>
                    </averageIntensity>
                    <averageIntensityOverAverageSigma>
                        <value>2.130000e+01</value>
                    </averageIntensityOverAverageSigma>
                    <averageSigma>
                        <value>4.717100e+01</value>
                    </averageSigma>
                    <completeness>
                        <value>9.900000e-01</value>
                    </completeness>
                    <maxResolution>
                        <value>3.720000e+00</value>
                    </maxResolution>
                    <minResolution>
                        <value>3.920000e+00</value>
                    </minResolution>
                    <percentageOverload>
                        <value>0.000000e+00</value>
                    </percentageOverload>
                    <rFactor>
                        <value>5.600000e+00</value>
                    </rFactor>
                    <redundancy>
                        <value>3.450000e+00</value>
                    </redundancy>
                </resolutionBin>
                <resolutionBin>
                    <IOverSigma>
                        <value>2.020000e+01</value>
                    </IOverSigma>
                    <averageIntensity>
                        <value>8.894600e+02</value>
                    </averageIntensity>
                    <averageIntensityOverAverageSigma>
                        <value>1.910000e+01</value>
                    </averageIntensityOverAverageSigma>
                    <averageSigma>
                        <value>4.647400e+01</value>
                    </averageSigma>
                    <completeness>
                        <value>9.900000e-01</value>
                    </completeness>
                    <maxResolution>
                        <value>3.550000e+00</value>
                    </maxResolution>
                    <minResolution>
                        <value>3.720000e+00</value>
                    </minResolution>
                    <percentageOverload>
                        <value>0.000000e+00</value>
                    </percentageOverload>
                    <rFactor>
                        <value>6.300000e+00</value>
                    </rFactor>
                    <redundancy>
                        <value>3.460000e+00</value>
                    </redundancy>
                </resolutionBin>
                <resolutionBin>
                    <IOverSigma>
                        <value>1.820000e+01</value>
                    </IOverSigma>
                    <averageIntensity>
                        <value>7.757620e+02</value>
                    </averageIntensity>
                    <averageIntensityOverAverageSigma>
                        <value>1.710000e+01</value>
                    </averageIntensityOverAverageSigma>
                    <averageSigma>
                        <value>4.527500e+01</value>
                    </averageSigma>
                    <completeness>
                        <value>9.900000e-01</value>
                    </completeness>
                    <maxResolution>
                        <value>3.390000e+00</value>
                    </maxResolution>
                    <minResolution>
                        <value>3.550000e+00</value>
                    </minResolution>
                    <percentageOverload>
                        <value>0.000000e+00</value>
                    </percentageOverload>
                    <rFactor>
                        <value>7.100000e+00</value>
                    </rFactor>
                    <redundancy>
                        <value>3.490000e+00</value>
                    </redundancy>
                </resolutionBin>
                <resolutionBin>
                    <IOverSigma>
                        <value>1.600000e+01</value>
                    </IOverSigma>
                    <averageIntensity>
                        <value>6.513570e+02</value>
                    </averageIntensity>
                    <averageIntensityOverAverageSigma>
                        <value>1.480000e+01</value>
                    </averageIntensityOverAverageSigma>
                    <averageSigma>
                        <value>4.394700e+01</value>
                    </averageSigma>
                    <completeness>
                        <value>9.900000e-01</value>
                    </completeness>
                    <maxResolution>
                        <value>3.260000e+00</value>
                    </maxResolution>
                    <minResolution>
                        <value>3.390000e+00</value>
                    </minResolution>
                    <percentageOverload>
                        <value>0.000000e+00</value>
                    </percentageOverload>
                    <rFactor>
                        <value>8.200000e+00</value>
                    </rFactor>
                    <redundancy>
                        <value>3.490000e+00</value>
                    </redundancy>
                </resolutionBin>
                <resolutionBin>
                    <IOverSigma>
                        <value>1.340000e+01</value>
                    </IOverSigma>
                    <averageIntensity>
                        <value>5.366330e+02</value>
                    </averageIntensity>
                    <averageIntensityOverAverageSigma>
                        <value>1.250000e+01</value>
                    </averageIntensityOverAverageSigma>
                    <averageSigma>
                        <value>4.303200e+01</value>
                    </averageSigma>
                    <completeness>
                        <value>9.800000e-01</value>
                    </completeness>
                    <maxResolution>
                        <value>3.140000e+00</value>
                    </maxResolution>
                    <minResolution>
                        <value>3.260000e+00</value>
                    </minResolution>
                    <percentageOverload>
                        <value>0.000000e+00</value>
                    </percentageOverload>
                    <rFactor>
                        <value>9.900000e+00</value>
                    </rFactor>
                    <redundancy>
                        <value>3.560000e+00</value>
                    </redundancy>
                </resolutionBin>
                <resolutionBin>
                    <IOverSigma>
                        <value>1.160000e+01</value>
                    </IOverSigma>
                    <averageIntensity>
                        <value>4.509080e+02</value>
                    </averageIntensity>
                    <averageIntensityOverAverageSigma>
                        <value>1.050000e+01</value>
                    </averageIntensityOverAverageSigma>
                    <averageSigma>
                        <value>4.282200e+01</value>
                    </averageSigma>
                    <completeness>
                        <value>9.800000e-01</value>
                    </completeness>
                    <maxResolution>
                        <value>3.030000e+00</value>
                    </maxResolution>
                    <minResolution>
                        <value>3.140000e+00</value>
                    </minResolution>
                    <percentageOverload>
                        <value>0.000000e+00</value>
                    </percentageOverload>
                    <rFactor>
                        <value>1.160000e+01</value>
                    </rFactor>
                    <redundancy>
                        <value>3.590000e+00</value>
                    </redundancy>
                </resolutionBin>
                <resolutionBin>
                    <IOverSigma>
                        <value>9.800000e+00</value>
                    </IOverSigma>
                    <averageIntensity>
                        <value>3.837450e+02</value>
                    </averageIntensity>
                    <averageIntensityOverAverageSigma>
                        <value>8.900000e+00</value>
                    </averageIntensityOverAverageSigma>
                    <averageSigma>
                        <value>4.319000e+01</value>
                    </averageSigma>
                    <completeness>
                        <value>9.800000e-01</value>
                    </completeness>
                    <maxResolution>
                        <value>2.940000e+00</value>
                    </maxResolution>
                    <minResolution>
                        <value>3.030000e+00</value>
                    </minResolution>
                    <percentageOverload>
                        <value>0.000000e+00</value>
                    </percentageOverload>
                    <rFactor>
                        <value>1.380000e+01</value>
                    </rFactor>
                    <redundancy>
                        <value>3.500000e+00</value>
                    </redundancy>
                </resolutionBin>
                <resolutionBin>
                    <IOverSigma>
                        <value>8.400000e+00</value>
                    </IOverSigma>
                    <averageIntensity>
                        <value>3.261080e+02</value>
                    </averageIntensity>
                    <averageIntensityOverAverageSigma>
                        <value>7.500000e+00</value>
                    </averageIntensityOverAverageSigma>
                    <averageSigma>
                        <value>4.338100e+01</value>
                    </averageSigma>
                    <completeness>
                        <value>9.800000e-01</value>
                    </completeness>
                    <maxResolution>
                        <value>2.850000e+00</value>
                    </maxResolution>
                    <minResolution>
                        <value>2.940000e+00</value>
                    </minResolution>
                    <percentageOverload>
                        <value>0.000000e+00</value>
                    </percentageOverload>
                    <rFactor>
                        <value>1.630000e+01</value>
                    </rFactor>
                    <redundancy>
                        <value>3.500000e+00</value>
                    </redundancy>
                </resolutionBin>
                <resolutionBin>
                    <IOverSigma>
                        <value>7.100000e+00</value>
                    </IOverSigma>
                    <averageIntensity>
                        <value>2.826900e+02</value>
                    </averageIntensity>
                    <averageIntensityOverAverageSigma>
                        <value>6.400000e+00</value>
                    </averageIntensityOverAverageSigma>
                    <averageSigma>
                        <value>4.421800e+01</value>
                    </averageSigma>
                    <completeness>
                        <value>9.800000e-01</value>
                    </completeness>
                    <maxResolution>
                        <value>2.770000e+00</value>
                    </maxResolution>
                    <minResolution>
                        <value>2.850000e+00</value>
                    </minResolution>
                    <percentageOverload>
                        <value>0.000000e+00</value>
                    </percentageOverload>
                    <rFactor>
                        <value>1.930000e+01</value>
                    </rFactor>
                    <redundancy>
                        <value>3.540000e+00</value>
                    </redundancy>
                </resolutionBin>
                <resolutionBin>
                    <IOverSigma>
                        <value>6.300000e+00</value>
                    </IOverSigma>
                    <averageIntensity>
                        <value>2.494080e+02</value>
                    </averageIntensity>
                    <averageIntensityOverAverageSigma>
                        <value>5.600000e+00</value>
                    </averageIntensityOverAverageSigma>
                    <averageSigma>
                        <value>4.464200e+01</value>
                    </averageSigma>
                    <completeness>
                        <value>9.800000e-01</value>
                    </completeness>
                    <maxResolution>
                        <value>2.700000e+00</value>
                    </maxResolution>
                    <minResolution>
                        <value>2.770000e+00</value>
                    </minResolution>
                    <percentageOverload>
                        <value>0.000000e+00</value>
                    </percentageOverload>
                    <rFactor>
                        <value>2.190000e+01</value>
                    </rFactor>
                    <redundancy>
                        <value>3.520000e+00</value>
                    </redundancy>
                </resolutionBin>
                <resolutionBin>
                    <IOverSigma>
                        <value>5.500000e+00</value>
                    </IOverSigma>
                    <averageIntensity>
                        <value>2.262700e+02</value>
                    </averageIntensity>
                    <averageIntensityOverAverageSigma>
                        <value>5.000000e+00</value>
                    </averageIntensityOverAverageSigma>
                    <averageSigma>
                        <value>4.566400e+01</value>
                    </averageSigma>
                    <completeness>
                        <value>9.900000e-01</value>
                    </completeness>
                    <maxResolution>
                        <value>2.630000e+00</value>
                    </maxResolution>
                    <minResolution>
                        <value>2.700000e+00</value>
                    </minResolution>
                    <percentageOverload>
                        <value>0.000000e+00</value>
                    </percentageOverload>
                    <rFactor>
                        <value>2.500000e+01</value>
                    </rFactor>
                    <redundancy>
                        <value>3.540000e+00</value>
                    </redundancy>
                </resolutionBin>
                <resolutionBin>
                    <IOverSigma>
                        <value>5.000000e+00</value>
                    </IOverSigma>
                    <averageIntensity>
                        <value>2.073510e+02</value>
                    </averageIntensity>
                    <averageIntensityOverAverageSigma>
                        <value>4.500000e+00</value>
                    </averageIntensityOverAverageSigma>
                    <averageSigma>
                        <value>4.632900e+01</value>
                    </averageSigma>
                    <completeness>
                        <value>9.700000e-01</value>
                    </completeness>
                    <maxResolution>
                        <value>2.560000e+00</value>
                    </maxResolution>
                    <minResolution>
                        <value>2.630000e+00</value>
                    </minResolution>
                    <percentageOverload>
                        <value>0.000000e+00</value>
                    </percentageOverload>
                    <rFactor>
                        <value>2.780000e+01</value>
                    </rFactor>
                    <redundancy>
                        <value>3.550000e+00</value>
                    </redundancy>
                </resolutionBin>
                <resolutionBin>
                    <IOverSigma>
                        <value>4.500000e+00</value>
                    </IOverSigma>
                    <averageIntensity>
                        <value>1.883090e+02</value>
                    </averageIntensity>
                    <averageIntensityOverAverageSigma>
                        <value>4.000000e+00</value>
                    </averageIntensityOverAverageSigma>
                    <averageSigma>
                        <value>4.689500e+01</value>
                    </averageSigma>
                    <completeness>
                        <value>9.900000e-01</value>
                    </completeness>
                    <maxResolution>
                        <value>2.500000e+00</value>
                    </maxResolution>
                    <minResolution>
                        <value>2.560000e+00</value>
                    </minResolution>
                    <percentageOverload>
                        <value>0.000000e+00</value>
                    </percentageOverload>
                    <rFactor>
                        <value>3.080000e+01</value>
                    </rFactor>
                    <redundancy>
                        <value>3.570000e+00</value>
                    </redundancy>
                </resolutionBin>
                <resolutionBin>
                    <IOverSigma>
                        <value>4.000000e+00</value>
                    </IOverSigma>
                    <averageIntensity>
                        <value>1.751910e+02</value>
                    </averageIntensity>
                    <averageIntensityOverAverageSigma>
                        <value>3.600000e+00</value>
                    </averageIntensityOverAverageSigma>
                    <averageSigma>
                        <value>4.831900e+01</value>
                    </averageSigma>
                    <completeness>
                        <value>9.700000e-01</value>
                    </completeness>
                    <maxResolution>
                        <value>2.450000e+00</value>
                    </maxResolution>
                    <minResolution>
                        <value>2.500000e+00</value>
                    </minResolution>
                    <percentageOverload>
                        <value>0.000000e+00</value>
                    </percentageOverload>
                    <rFactor>
                        <value>3.420000e+01</value>
                    </rFactor>
                    <redundancy>
                        <value>3.600000e+00</value>
                    </redundancy>
                </resolutionBin>
                <resolutionBin>
                    <IOverSigma>
                        <value>3.700000e+00</value>
                    </IOverSigma>
                    <averageIntensity>
                        <value>1.633840e+02</value>
                    </averageIntensity>
                    <averageIntensityOverAverageSigma>
                        <value>3.300000e+00</value>
                    </averageIntensityOverAverageSigma>
                    <averageSigma>
                        <value>4.945600e+01</value>
                    </averageSigma>
                    <completeness>
                        <value>9.800000e-01</value>
                    </completeness>
                    <maxResolution>
                        <value>2.400000e+00</value>
                    </maxResolution>
                    <minResolution>
                        <value>2.450000e+00</value>
                    </minResolution>
                    <percentageOverload>
                        <value>0.000000e+00</value>
                    </percentageOverload>
                    <rFactor>
                        <value>3.740000e+01</value>
                    </rFactor>
                    <redundancy>
                        <value>3.540000e+00</value>
                    </redundancy>
                </resolutionBin>
                <resolutionBin>
                    <IOverSigma>
                        <value>3.400000e+00</value>
                    </IOverSigma>
                    <averageIntensity>
                        <value>1.544050e+02</value>
                    </averageIntensity>
                    <averageIntensityOverAverageSigma>
                        <value>3.100000e+00</value>
                    </averageIntensityOverAverageSigma>
                    <averageSigma>
                        <value>5.002800e+01</value>
                    </averageSigma>
                    <completeness>
                        <value>9.700000e-01</value>
                    </completeness>
                    <maxResolution>
                        <value>2.350000e+00</value>
                    </maxResolution>
                    <minResolution>
                        <value>2.400000e+00</value>
                    </minResolution>
                    <percentageOverload>
                        <value>0.000000e+00</value>
                    </percentageOverload>
                    <rFactor>
                        <value>4.040000e+01</value>
                    </rFactor>
                    <redundancy>
                        <value>3.610000e+00</value>
                    </redundancy>
                </resolutionBin>
                <resolutionBin>
                    <IOverSigma>
                        <value>3.100000e+00</value>
                    </IOverSigma>
                    <averageIntensity>
                        <value>1.456390e+02</value>
                    </averageIntensity>
                    <averageIntensityOverAverageSigma>
                        <value>2.800000e+00</value>
                    </averageIntensityOverAverageSigma>
                    <averageSigma>
                        <value>5.167000e+01</value>
                    </averageSigma>
                    <completeness>
                        <value>9.600000e-01</value>
                    </completeness>
                    <maxResolution>
                        <value>2.300000e+00</value>
                    </maxResolution>
                    <minResolution>
                        <value>2.350000e+00</value>
                    </minResolution>
                    <percentageOverload>
                        <value>0.000000e+00</value>
                    </percentageOverload>
                    <rFactor>
                        <value>4.430000e+01</value>
                    </rFactor>
                    <redundancy>
                        <value>3.480000e+00</value>
                    </redundancy>
                </resolutionBin>
                <resolutionBin>
                    <IOverSigma>
                        <value>1.120000e+01</value>
                    </IOverSigma>
                    <averageIntensity>
                        <value>4.961110e+02</value>
                    </averageIntensity>
                    <averageSigma>
                        <value>4.448300e+01</value>
                    </averageSigma>
                    <completeness>
                        <value>9.800000e-01</value>
                    </completeness>
                    <maxResolution>
                        <value>2.300000e+00</value>
                    </maxResolution>
                    <minResolution>
                        <value>1.200000e+01</value>
                    </minResolution>
                    <percentageOverload>
                        <value>0.000000e+00</value>
                    </percentageOverload>
                    <rFactor>
                        <value>1.110000e+01</value>
                    </rFactor>
                    <redundancy>
                        <value>3.490000e+00</value>
                    </redundancy>
                </resolutionBin>
            </statistics>
            <strategySummary>
                <completeness>
                    <value>9.830000e-01</value>
                </completeness>
                <iSigma>
                    <value>2.800000e+00</value>
                </iSigma>
                <rankingResolution>
                    <value>1.460000e+00</value>
                </rankingResolution>
                <redundancy>
                    <value>3.490000e+00</value>
                </redundancy>
                <resolution>
                    <value>2.300000e+00</value>
                </resolution>
                <resolutionReasoning>
                    <value>Resolution limit is set by the initial image resolution</value>
                </resolutionReasoning>
                <totalDataCollectionTime>
                    <value>1.462200e+02</value>
                </totalDataCollectionTime>
                <totalExposureTime>
                    <value>3.720000e+00</value>
                </totalExposureTime>
            </strategySummary>
        </collectionPlan>
    </suggestedStrategy>"""

